# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gary C.F. Lee
email: garyleecf[at]gmail[dot]com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my webpage, where I showcase my works and share updates on my technical, scientific, and engineering endeavors. Stay tuned for updates and new content!
twitter_username: rfunengineer
github_username: garyleecf
minimal_mistakes_skin: dark #default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Singapore # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Gary Lee"
  avatar : "/assets/images/PersonalHeadshot.jpg"
  bio    : "I am an adventuring innovator (AI researcher) specializing in deep learning, signal processing, and wireless communication, with a passion for exploring new solutions to old long-standing problems."
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: "https://scholar.google.com/citations?user=-k6WQI0AAAAJ&hl=en"
    - label: "LinkedIn"
      icon: "fas fa-fw fa-linkedin-square"
      url: "https://www.linkedin.com/in/garyleecf/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rfunengineer"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/garyleecf/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/reallyfun_engineer/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rfunengineer"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/garyleecf/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/reallyfun_engineer/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
